#!/bin/sh

#PBS -N right_optimized

#PBS -l nodes=1:ppn=8,mem=46gb
#PBS -l walltime=476:00:00

#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M kjflynn@umich.edu

#PBS -q first
#PBS -l qos=flux
#PBS -q fluxod
#PBS -A pschloss_fluxod

echo "ncpus-2.pbs"
cat $PBS_NODEFILE

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`

module load R
Rscript code/right_optimized.R



echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit